config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  get 'welcome/index'

  # create routes for documents
  resources :docs
  
  # main page for logged-in users
  authenticated :user do
    root 'docs#index', as: 'authenticated_root'
  end
  
  # view welcome index on main page
  root 'welcome#index'
  
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/doc.rb
class Doc < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :docs       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
    before_action :find_doc, only: [:show, :edit, :update, :destroy]
    
    # display all documents by newest created
    def index
        @docs = Doc.where(user_id: current_user).order("created_at DESC")
    end
    
    # find document by its id and display its title & contents
    def show
    end
    
    # create new document with its parameters title & content
    def create
        @doc = current_user.docs.build(doc_params)
        
        # if document is sucessfully saved, redirect to the new document
        if @doc.save
            redirect_to @doc
        # if document is not saved, render form again to create new document
        else   
            render 'new'
        end    
    end
    
    # new document view
    def new
        @doc = current_user.docs.build
    end
    
    # update an existing document
    def update
        # if document is sucessfully updated, redirect to the document
        if @doc.update(doc_params)
            redirect_to @doc
        # if document is not updated, render form again to edit document
        else
            render 'edit'
        end    
    end
    
    # find document by its id and edit its contents
    def edit
    end
 
    # find document by its id and delete it, then redirect to all documents index
    def destroy
        @doc.destroy
        redirect_to docs_path
    end
    
    private
    
        def find_doc
            @doc = Doc.find(params[:id])
        end
        
        def doc_params
            params.require(:doc).permit(:title, :content)
        end    

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
// form partial for document instance variable (@doc)
.container
    = simple_form_for(@doc, html: { class: 'form-horizontal' }) do |f|
        = f.input :title
        = f.cktext_area :content
        = f.button :submit, class: "btn btn-success create-edit-form-btn"

app/views/docs/edit.html.haml
%h1 Edit Document
// render form partial
= render 'form'

// leave edit form and return to document
%p= link_to "Cancel", doc_path, class: "btn btn-primary"

app/views/docs/index.html.haml
// If a user has created documents, display the documents. Otherwise, show link to create new document.
-unless @docs.blank?
    // loop through each document and display its title (link) and contents preview
    - @docs.each do |doc|
        %a.well-docs{ href: (url_for [doc]) }
            .well
                %h2= doc.title
                %p= "Created " + time_ago_in_words(doc.created_at) + " ago"
                %p= truncate(doc.content, length:100)
- else
    %h2 Create your first document
    %p Edit, organize and save your work!
    // link to create new document    
    %p= link_to "Create New", new_doc_path, class: "btn btn-sm btn-success"

app/views/docs/new.html.haml
%h1 New Document
// render form partial
= render 'form'

// leave new form and return to all documents index
%p= link_to "Cancel", docs_path, class: "btn btn-primary margin-top"

app/views/docs/show.html.haml
// Display document title and content
%h1= @doc.title
%p= simple_format(@doc.content)

// links to view all docs, edit doc, or delete doc (with confirmation alert)
%span= link_to "All Documents", docs_path, class: "btn btn-sm btn-info"
%span= link_to "Edit Document", edit_doc_path(@doc), class: "btn btn-sm btn-primary"
%span= link_to "Delete Document", doc_path(@doc), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-danger"

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
%head
  %meta(charset="utf-8")
  %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
  %meta(name="viewport" content="width=device-width, initial-scale=1.0")
  %title FileCabinet
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true 
  %link{:rel => "stylesheet", :href => "http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"}
  = csrf_meta_tags
   
%body

%body
  %nav.navbar.navbar-default.navbar-static-top
    .container
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", type: "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{href: root_path} File Cabinet
      .collapse.navbar-collapse.navbar-ex1-collapse  
        %ul.nav.navbar-nav.pull-right
          - if user_signed_in?
            %li= link_to "Create Document", new_doc_path
            %li= link_to "Sign Out", destroy_user_session_path, method: :delete
          - else  
            %li= link_to "Log In", new_user_session_path
            %li= link_to "Sign Up", new_user_registration_path
  .row      
    .container      
        
      %p.notice= notice
      %p.alert= alert
    
      = yield

app/views/welcome/index.html.haml
// static landing page
// %h1 This is the welcome page!

.jumbotron
    %h1 File Cabinet
    %p Your work. <span>Organized, always.</span>
    %p= link_to "Get started", new_user_registration_path, class: "btn btn-md btn-success"